name: checkov smoke tests
on:
  workflow_dispatch:

jobs:
  boost:
    name: Checkov latest
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          cat ~/.docker/config.json
          TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)
          curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
      - name: Clone
        uses: actions/checkout@v3      
      - name: 'Checkov latest'
        continue-on-error: true
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/checkov
          api_token: ${{ secrets.BOOST_API_TOKEN }}
        env:
          BOOST_SCANNER_REGISTRY_REPO: https://github.com/FranckBoostOrg/scanner-registry.git#flr-test
